dist: xenial
language: python
python:
- '3.7'
install:
- pip install mkdocs
script:
- mkdocs build
addons:
  ssh_known_hosts: deploy.icymind.com:11235
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 travis_rsa
- ssh-add travis_rsa
deploy:
  provider: script
  script: rsync -raz -e 'ssh -p 11235 -o StrictHostKeyChecking=no -o CheckHostIP=no'
    $TRAVIS_BUILD_DIR/site/* simon@deploy.icymind.com:/srv/www/icymind.com/wiki
before_install:
- openssl aes-256-cbc -K $encrypted_b7eee5ba7c6b_key -iv $encrypted_b7eee5ba7c6b_iv
  -in travis_rsa.enc -out travis_rsa -d
