site_name: icy wiki
repo_url: 'https://github.com/icymind/wiki'
site_author: 'icymindt@gmail.com'
markdown_extensions:
  - toc:
      toc_depth: 0
theme: readthedocs
extra_css:
  - extra/custom.css
extra_javascript:
  - extra/custom.js
